# to build image:
# > docker-compose build

# to run container (and keep atached to the container)
# > docker-compose up [<service_name>]

# to run container as a daemon
# > docker-compose up -d [<service_name>]
# to attach to daemon container
# > docker exec -it <container_id> bash

# to stop the started container
# > docker-compose stop [<service_name>]

# to stop and remove the started container
# > docker-compose down [<service_name>]

version: "3"
services:
  idrink:
    image: idrink
    #restart: always
    tty: true
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        http_proxy : "http://barc.proxy.corp.sopra:8080/"
        https_proxy : "http://barc.proxy.corp.sopra:8080/"
    ports:
      - 8081:8081
    environment:
      - PORT=8081
